spring:
  application:
    name:  service-proxy

  ##GATEWAY CONFIGURATIONS
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/company-service/**
          filters:
            - StripPrefix=1
          metadata:
            cors:
              allowedOrigins:
                - http://localhost:3000
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
              allowedHeaders:
                - "*"

        ## service1
        - id: service1
          uri: lb://service1
          predicates:
            - Path=/service1/**
          filters:
            - StripPrefix=1
          # Move metadata here
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - '*'
              allowedHeaders: '*'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


